package com.smartcampus.demo.service;

import com.smartcampus.demo.entity.Resource;
import com.smartcampus.demo.repository.ResourceRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ResourceServiceTest {

    @Mock
    private ResourceRepository resourceRepository;

    @InjectMocks
    private ResourceService resourceService;

    private Resource testResource;

    @BeforeEach
    void setUp() {
        testResource = new Resource();
        testResource.setId("1");
        testResource.setName("Test Room");
        testResource.setType("Classroom");
        testResource.setCategory("Academic");
        testResource.setBuilding("Building A");
        testResource.setFloor("1");
        testResource.setCapacity(30);
        testResource.setStatus(Resource.Status.ACTIVE);
        testResource.setCondition(Resource.Condition.GOOD);
        testResource.setAssetTag("FAC-0001");
        testResource.setValue(new BigDecimal("10000.00"));
        testResource.setPurchaseDate(LocalDate.now());
        testResource.setWarrantyExpiry(LocalDate.now().plusYears(1));
    }

    @Test
    void testFindAll() {
        when(resourceRepository.search(anyString(), any(), anyString()))
            .thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findAll("Classroom", 20, "Building A");

        assertNotNull(result);
        assertEquals(1, result.size());
        assertEquals("Test Room", result.get(0).getName());
    }

    @Test
    void testFindById() {
        when(resourceRepository.findById("1")).thenReturn(Optional.of(testResource));

        Resource result = resourceService.findById("1");

        assertNotNull(result);
        assertEquals("Test Room", result.getName());
    }

    @Test
    void testFindByIdNotFound() {
        when(resourceRepository.findById("999")).thenReturn(Optional.empty());

        assertThrows(RuntimeException.class, () -> resourceService.findById("999"));
    }

    @Test
    void testSave() {
        when(resourceRepository.save(any(Resource.class))).thenReturn(testResource);
        when(resourceRepository.count()).thenReturn(0L);

        Resource result = resourceService.save(testResource);

        assertNotNull(result);
        assertEquals("FAC-0001", result.getAssetTag());
        verify(resourceRepository).save(any(Resource.class));
    }

    @Test
    void testSaveWithAutoGeneratedAssetTag() {
        testResource.setAssetTag(null);
        when(resourceRepository.save(any(Resource.class))).thenReturn(testResource);
        when(resourceRepository.count()).thenReturn(5L);

        Resource result = resourceService.save(testResource);

        assertNotNull(result);
        verify(resourceRepository).save(any(Resource.class));
    }

    @Test
    void testFindByCategory() {
        when(resourceRepository.findByCategory("Academic")).thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findByCategory("Academic");

        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void testFindByStatus() {
        when(resourceRepository.findByStatus(Resource.Status.ACTIVE)).thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findByStatus(Resource.Status.ACTIVE);

        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void testFindAvailable() {
        when(resourceRepository.findByStatusActive()).thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findAvailable();

        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void testAssign() {
        when(resourceRepository.findById("1")).thenReturn(Optional.of(testResource));
        when(resourceRepository.save(any(Resource.class))).thenReturn(testResource);

        Resource result = resourceService.assign("1", "user123");

        assertNotNull(result);
        assertEquals("user123", result.getAssignedTo());
    }

    @Test
    void testUnassign() {
        testResource.setAssignedTo("user123");
        when(resourceRepository.findById("1")).thenReturn(Optional.of(testResource));
        when(resourceRepository.save(any(Resource.class))).thenReturn(testResource);

        Resource result = resourceService.unassign("1");

        assertNotNull(result);
        assertNull(result.getAssignedTo());
    }

    @Test
    void testUpdateCondition() {
        when(resourceRepository.findById("1")).thenReturn(Optional.of(testResource));
        when(resourceRepository.save(any(Resource.class))).thenReturn(testResource);

        Resource result = resourceService.updateCondition("1", Resource.Condition.FAIR);

        assertNotNull(result);
        assertEquals(Resource.Condition.FAIR, result.getCondition());
    }

    @Test
    void testUpdateStatus() {
        when(resourceRepository.findById("1")).thenReturn(Optional.of(testResource));
        when(resourceRepository.save(any(Resource.class))).thenReturn(testResource);

        Resource result = resourceService.updateStatus("1", Resource.Status.UNDER_MAINTENANCE);

        assertNotNull(result);
        assertEquals(Resource.Status.UNDER_MAINTENANCE, result.getStatus());
    }

    @Test
    void testFindMaintenanceDue() {
        when(resourceRepository.findByWarrantyExpiryBefore(any())).thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findMaintenanceDue();

        assertNotNull(result);
    }

    @Test
    void testFindByBuilding() {
        when(resourceRepository.findByBuilding("Building A")).thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findByBuilding("Building A");

        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void testFindByFloor() {
        when(resourceRepository.findByFloor("1")).thenReturn(Arrays.asList(testResource));

        List<Resource> result = resourceService.findByFloor("1");

        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void testBulkCreate() {
        Resource resource2 = new Resource();
        resource2.setName("Test Room 2");
        
        when(resourceRepository.saveAll(anyList())).thenReturn(Arrays.asList(testResource, resource2));
        when(resourceRepository.count()).thenReturn(0L);

        List<Resource> result = resourceService.bulkCreate(Arrays.asList(testResource, resource2));

        assertNotNull(result);
        assertEquals(2, result.size());
    }

    @Test
    void testBulkDelete() {
        when(resourceRepository.findByIdIn(Arrays.asList("1", "2"))).thenReturn(Arrays.asList(testResource));
        
        resourceService.bulkDelete(Arrays.asList("1", "2"));

        verify(resourceRepository).deleteAll(anyList());
    }
}