spring.application.name=smartCampusHub
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_hub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=asQW12!@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.security.oauth2.client.registration.google.client-id=114003028134-975n8dsn6tcieuj6ub9tg8l7sfkg3eej.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

jwt.secret=verysecretkeyverysecretkeypasindupiyumalsliitpafassignment
jwt.expiration-ms=3600000

admin.email=sasikashehan2332@gmail.com
student.email=sasikashehan6690@gmail.com
lecturer.email=codm62529@gmail.com
technician.email=slvideos5000@gmail.com
manager.email=kumarakumara4541@gmail.com

# Cloudinary Configuration

cloudinary.cloud-name=dryvai4xw
cloudinary.api-key=119589611249918
cloudinary.api-secret=2kRUqPeBOe8W8iTbY-2xbJ9avkY
